### PR TITLE
chore: tests

### PR DESCRIPTION
**Pull request by JasonLantz**

### CODE REVIEW

**Comment by wyseguyonline** [comment]
LGTM

**Comment by StommePoes** [comment]
Did you want to update to match component archetype (not call react/dom from the CDN) as well?

**Comment by StommePoes** [comment]
Buttons don't need tabindex, they are natural focusables, so that can be removed. If you're setting tabindex=-1 to all focusables on the page when the modal is open (which is an option though it's expensive javascript-wise), you can just add and remove the whole "tabindex=-1" thing as a whole.

When it's controlling something, like a modal, it needs two attributes:
aria-expanded (set to the string "false" when the modal isn't open, "true" when it is) and 
aria-controls (set to the string of the id of the modal)


```<span class="pe-sr-only">close modal button</span>```
Buttons get announced as buttons already so we don't need to call buttons buttons or links links, the assistive tech does that for us (why semantics are important). So instead I would say this button text should be just "Close dialog" (with internationalisation capabilities).

The dialog role belongs on the thing being described by the heading and texts inside the modal.
I know React forces us to write way too much HTML, but if we didn't have to deal with React, it would look like this
```
<div role="dialog" id="origamiModal" aria-labelledby="modalHeaderText" (possibly also aria-describedby="modalBodyText" if it's just a small text modal)>
  <div>
    <hx id="modalHeaderText">I am header, hear me r0aR</hx>
    <p (possibly id="modalBodyText")>I am description, me most goodry importante</p>
  </div>
</div>
```

So we don't need all the other aria-labelledbys, 1 is enough. The extra divs you can have if you want for styling but they don't need to hold any information or aria-anythings.

**Comment by JasonLantz** [comment]
- ∆ the cdn react dependency in index.html.
- killed aria-labelby except for modalContent.
- removed trapFocus method.
- updated close button text to "close dialog"
- aria dialog on modalContent.
- updated tests

thx Mallory!

**Pull request merged**
